### ISSUE TITLE
Wrong string in the dialogue of renaming a collection

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/Scryer#100]
Step:
rename a collection from the "collection view"

Expect:
refer to 3.1-C: it should be "CANCEL" or "OK" for the user to confirm
![ux spec 3 1c](https://user-images.githubusercontent.com/13250512/45202241-f0446a00-b2aa-11e8-9283-36c18aa52a56.png)

Actual result:
it's CANCEL and "ADD" currently
![photo_2018-09-07_14-33-24](https://user-images.githubusercontent.com/13250512/45202257-fdf9ef80-b2aa-11e8-8148-6ba89de9f363.jpg)

Nightly build 202
Android 8.0.0
S8+

**Comment by weslyhuang** [comment]
2nd level menu so S1.

**Comment by weslyhuang** [comment]
Two points to enter this point:

1. collection view --> hamburger button -> rename (spec 3.1-c)
2. home view --> long press a collection --> rename (didn't find it in spec)

should we expect the same menu here? @ChenMorpheus

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2 
Android 8.1.0
Scryer 1.0(364).nightly
