### ISSUE TITLE
The new collection should be in the upper right of your collection

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#101]
STR
1. Launch Scryer
2. Tap + Create new
3. Enter texts 
4. Tap ADD

Expected Result:
 - The new collection should be in the upper right of your collection

Actual Result: 
 - The new collection should be at the bottom of your collection

Scryer 1.0(202).nightly
Pixel 2 with Android 8.1.0

**Comment by pharspher** [comment]
2.1.E
"Collections displays based on the time they're created, old to new, top to down."

**Comment by weslyhuang** [comment]
S1 if not follow the spec, but per Roger's comment, is it a valid issue?

**Comment by ChenMorpheus** [comment]
I've consulted everyone and got the conclusion here:

Collections display based on the time they are created, old to new, top to down. Some extract rules here: 
1. "Unsorted" always be the first one in Home view 
2. "Create new" always be the last one in Home view and Sorting panel 
3. Suggestions always follow the latest created to display

![image](https://user-images.githubusercontent.com/18019946/45287955-1a509300-b51c-11e8-8765-4131a98a8531.png)

**Comment by pharspher** [comment]
implemented in #138

**Comment by cynthiatang** [comment]
Pixel2 
Android 8.1.0
ScreenshotGo 1.0(454).nightly
