### ISSUE TITLE
Wrong string - it should be Quick Access, not Quick access

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#102]
Launch Scryer

Expected Result
 - Quick Access 

Actual Result 
 - Quick access

Scryer 1.0(202).nightly
Pixel 2 with Android 8.1.0

**Comment by benjamin-cheng** [comment]
I guess it's not a issue since it's matched the string id definition from @ChenMorpheus

**Comment by weslyhuang** [comment]
S1 if not complying UX spec, also 1st level menu.

**Comment by ChenMorpheus** [comment]
Consulted with engineer and decided to keep it "Quick access" since the time of translation is a concern.

**Comment by weslyhuang** [comment]
invalid per ux comment above, close.
