### ISSUE TITLE
Prompt to ask for permission for FAB not shown during onboarding

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Scryer#117]
Prerequisite:
N/A

STR:
1. Launch Scryer for the first time
2. Tap LET'S LOAD IT!
3. Tap ALLOW on storage permission prompt

Expected result:
According to spec 7.1 onboarding - figure C, permission prompt should show up asking user to go to grant page to allow FAB or skip by tapping "LATER".

Actual result:
Prompt asking user to give screenshot button a try, with only one button - "OK"

Reproduce Rate: 100%

Device: Nexus 5
Scryer Ver.: 1.0(202).nightly
Android Ver.: 6.0.1
WebView: 68.0.3440.9

Clip:
https://drive.google.com/open?id=1peM3Ufar9taaFyPGG0bCaqdi80PQc2At

**Comment by pharspher** [comment]
If the app is installed through Google Play, overlay permission (for FAB) is automatically granted by the system, there's no need to ask for the permission. This scenario is described in spec 7.2

**Comment by weslyhuang** [comment]
permission handling should be important as P1.

**Comment by weslyhuang** [comment]
@mlwang32  @cynthiatang would you help confirm if it's the case pointed by Roger? is it still a valid issue? Thanks.

**Comment by mlwang32** [comment]
Scryer v1.0(202).nightly installed from google store, FAB access granted by default, issue closed.
