### ISSUE TITLE
No action after tapping Menu icon in "All in collection view"

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#12]
1. Launch Scryer
2. Tap View All for quick access
3. Tap Menu icon

Actual result
 - no action
 - https://drive.google.com/open?id=19D7wLNbuTYvqDEw7qaxofSFRAREKloAn

Expected result:
 - open Menu

Reproduce Rate 10/10

Build ID: 65
Pixel2
Android 8.1.0

**Comment by weslyhuang** [comment]
1. 1st menu icon so S1
2. works for me on build 160. (Android 8.0.0, Galaxy S8+)

**Comment by cynthiatang** [comment]
Pixel 2 
Android 8.1.0
Screenshot 0.8(445)
