### ISSUE TITLE
Failed to show the collection in "All" collection

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#121]
STR:
 1. Launch Scryer
 2. Tap VIEW ALL
 3. Tap Menu
 4. Tap Collection info

Expected Result
 - Show the collection info (UX Spec: 2.1 C)

Actual Result 
 - It doesn't show the collection info
 - https://drive.google.com/open?id=1KF6XsMl-w_vyyk9ogVcBuvCCZSPsWm0t

Reproduce Rate: 10/10

Scryer 1.0(210).nightly
Pixel 2
Android 8.1.0
WebView 68.0.3440.91

**Comment by benjamin-cheng** [comment]
It's related to #12

**Comment by ChenMorpheus** [comment]
Compared to the other collections, the valid information in "View all" collection is the number of screenshots and storage used. However, the former has displayed as the separator. After discussion, we decided to remove the overflow menu, and we'll provide the info of storage used if users ask for the information in open-beta.

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2
Android 8.1.0
ScreenshotGo 1.0(346).nightly
