### ISSUE TITLE
The string should be "Unsorted" in Home view and Collection view

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#13]
UX spec:
<img width="281" alt="screen shot 2018-08-21 at 2 46 50" src="https://user-images.githubusercontent.com/12458450/44385500-2d41fa00-a552-11e8-895d-b0731fc90b49.png">

Actual result
 - 
<img src="https://user-images.githubusercontent.com/12458450/44385563-595d7b00-a552-11e8-8222-009075c6512d.png" width="30%" height="30%">                    <img src="https://user-images.githubusercontent.com/12458450/44385564-59f61180-a552-11e8-82fa-535a815e99e3.png" width="30%" height="30%">           

Build ID: 65
Pixel2
Android 8.1.0

**Comment by weslyhuang** [comment]
S1 as 1st level menu.
valid bug per String IDs table;
https://docs.google.com/spreadsheets/d/1NHL3Yihhb2R3Y2iH4Wm1DiZ_gZfuUq_oz0-kunBwo1I/edit?ts=5b8076ca#gid=0

**Comment by cynthiatang** [comment]
Verified: Fixed
Pixel 2 
Android 8.1.0
Screenshot 0.8(445)
