### ISSUE TITLE
Would be nice to show the inconsistent name after creating a new collection 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#14]
Display English in Uppercase

1. Create a new collection 
2. Enter "testTEST"

Actual Result
 - It would show TESTTEST in Home View
 - It would show testTEST in collection View
 - Video: https://drive.google.com/open?id=1kIwJV6JSAFSXaSI6E7ArZaBoyv04YkP6

Build ID: 65
Pixel2
Android 8.1.0

**Comment by weslyhuang** [comment]
Good catch! Seems we've enforced uppercase for Homeview but not Collection view? 

S1 but may need UX's input for priority. (remember it's Visual suggestion to uppercase the Homeview title)

@ChenMorpheus would you help comment?

**Comment by ChenMorpheus** [comment]
Now the implementation is correct. All caps only apply to sorting panel and home view, where display collections in visual blocks. This helps create the contrast between the name and the background image.

![image](https://user-images.githubusercontent.com/18019946/45082006-fa3f5f00-b12a-11e8-9a17-39ac051f5ef5.png)

Release note
![image](https://user-images.githubusercontent.com/18019946/45082823-cd8c4700-b12c-11e8-95c9-d96093bd01ca.png)

**Comment by weslyhuang** [comment]
thanks Morphsue, then close per comment above.

**Comment by cynthiatang** [comment]
Verified: Fixed
Pixel 2 
Android 8.1.0
Screenshot 0.8(445)
