### ISSUE TITLE
Header font size in welcome and error page

### ISSUE THREAD

**Issue by fangshih** [mozilla-tw/Scryer#141]
Current build seems a little small. Can we make sure is using H1 for the header? Thanks.
![screen shot 2018-09-12 at 12 00 00 pm](https://user-images.githubusercontent.com/4862573/45401522-94e7f280-b683-11e8-9088-47dc888f80c7.png)

Same as the error page. the header should be using H3 in this one. 
![screen shot 2018-09-12 at 12 05 27 pm](https://user-images.githubusercontent.com/4862573/45401713-90700980-b684-11e8-9b65-d24cf8d47faa.png)

**Comment by weslyhuang** [comment]
guess this is P1 but not necessarily P0?

**Comment by pharspher** [comment]
fix in #142

**Comment by weslyhuang** [comment]
removed need triage as fixed.
