### ISSUE TITLE
The string should be "Are you sure? This action cannot be undone."

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#15]
1. Launch Scryer 
2. Long press a screenshot in Quick Access field
3. Tap Delete

Expected Result:
 - 
 <img width="309" alt="screen shot 2018-08-21 at 6 19 21" src="https://user-images.githubusercontent.com/12458450/44396220-cda61780-a56e-11e8-8e44-ed8c15733d3d.png">

Actual Result:
 -
<img src="https://user-images.githubusercontent.com/12458450/44396388-52913100-a56f-11e8-9a1e-da1ea57acba8.png" width="50%" height="50%">      

Build ID: 65
Pixel2
Android 8.1.0

**Comment by weslyhuang** [comment]
1. for 2.3-F, the UX comment under the screen != the words in the dialogue window.
2. the current behavior aligns with the UX comment, but not the dialogue window. Looks ok to me as I thought the UX comment takes the priority.

@ChenMorpheus , would you help confirm? thanks.

**Comment by ChenMorpheus** [comment]
The copy should be "Are you sure? This action cannot be undone." As for the UX spec, I only updated the string but didn't update the comment below the screen. I've updated the comment. Nice catch.

**Comment by weslyhuang** [comment]
oh then it's a valid bug now since the current behavior follows your original comment. (which in fact provides more information)

**Comment by weslyhuang** [comment]
build 160. right msg but still missing the "file size", per UX spec.

2nd level UI so S1. guess P2 might be ok if huge effort w/o enough time.

**Comment by weslyhuang** [comment]
@cynthiatang is this the same as #42? tks.

**Comment by cynthiatang** [comment]
No, it is not the same as #42. But I think developers fixed those issue yesterday.

![screenshot_20180905-164414](https://user-images.githubusercontent.com/12458450/45082065-1e9b3b80-b12b-11e8-841c-d9af4415320c.png)

**Comment by cynthiatang** [comment]
Verified: Fixed

Scryer 1.0(210).nightly
Pixel 2
Android 8.1.0
WebView 68.0.3440.91
