### ISSUE TITLE
Failed to move screenshots to a collection (Vivo 1606 with Androi 6.0.1 and Oppo A37f with Android 5.1.1)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#152]
1. Launch Scryer
2. Long tap a screenshot 
3. Tap Move to 
4. Tap a collection

Expected Result
 - User can move a screenshot to a collection

Actual Result
 - User cannot move a screenshot to a collection
 - Video: https://drive.google.com/open?id=198hQ9uVt4-KJmDstSP21wjDDddP2eKHA

Reproduce Rate: 5/5

Scryer 1.0(294).nightly
Vivo 1606
Android 6.0.1

**Comment by weslyhuang** [comment]
works for me (S8+, Android 8.0.0, build 294), is this also device specific? @cynthiatang.
should be a basic scenario, need to check more.

**Comment by cynthiatang** [comment]
Vivo 1606 with Android 6.0.1 only

**Comment by pharspher** [comment]
fix in #159

**Comment by cynthiatang** [comment]
Verified: Fixed

Vivo 1606 
Android 6.0.1
ScreenshotGo 1.0(346).nightly
