### ISSUE TITLE
integrate in-product URL of SUMO page (settings --> about)

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/Scryer#160]
add a ticket for tracking. need to confirm the URL.

**Comment by weslyhuang** [comment]
confirmed the link from SUMO team[1], it's:

https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/screenshot-help

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1487764#c2

**Comment by cynthiatang** [comment]
Verified: fixed

Pixel2 
Android8.1.0
ScreenshotFo 1.0(346).nightly
