### ISSUE TITLE
No on-boarding page for the first time user (OPPO A37f with Android 5.1.1)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#53]
1. Install Scryer in OPPO A37f with Android 5.1.1
2. Launch Scryer

Expected result:
 - Show onboarding page 

Actual result:
 - No onboarding page 
 - There is a message "Give the screenshot button a try to see what'll happen"
 - https://drive.google.com/open?id=1Yu2_IlYvMQ97KxknZNnFSgZoa21EHABZ

Scryer 1.0 (160).debug
OPPO A37f 
Android 5.1.1

**Comment by weslyhuang** [comment]
1st level so S1, also mvp so P1

**Comment by mlwang32** [comment]
Same issue for Advan i5C (android 5.1)

**Comment by cynthiatang** [comment]
Verified: Fixed

OPPO A37f
Android 5.1.1
ScreenshotGo 1.0(454).nightly
