### ISSUE TITLE
The dialogue "Capturing permission" doesn't prompt when users hit FAB again

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#67]
1. Install Scryer
2. Launch Scryer
3. Tap ALLOW
4. Tap GTO TO GRANT PAGE
5. Enable Permit drawing over other apps
6. Tab system Back key
7. Tap FAB
8. Tap START NOW
9. Tap FAB again

Expected Result
 - If users don't check "don't show again" and hit start now, the dialogue prompts when users hit FAB again (UX spec: 7.1 K)

Actual Result:
 - The dialogue doesn't prompt when users hit FAB again 
 - Video: https://drive.google.com/open?id=1teBE6HW2joM2qgxRcEnO_hgGZKKPs0Jz

Scryer 1.0(173).debug
Pixel2 
Android 8.1.0

**Comment by weslyhuang** [comment]
I believe it's important enough to be S1 and even P1 (permission flow), but the team may want to take a look about the priority.
