### ISSUE TITLE
Need a short description and a thumbnail for Share with friends

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#73]
1. Launch Scryer
2. Go to Menu -> Settings -> Share with friends -> Gmail

Expected Result
 - The message contains a short description and a thumbnail directing to the download page

Actual Result:
 - The message doesn't contain a short description and a thumbnail directing to the download page

![screenshot_20180905-151648](https://user-images.githubusercontent.com/12458450/45077198-20f79880-b11f-11e8-97d5-53fed6db41e4.png)

Scryer 1.0(173).debug
Pixel2
Android 8.1.0

**Comment by weslyhuang** [comment]
not complying UX spec 6.1-G, but is it only happen with Gmail? we have some special case with Gmail before (Rocket). @cynthiatang

**Comment by benjamin-cheng** [comment]
I've requested this string, however, it's marketing related and it should be defined with other onboarding strings. Need @ChenMorpheus to confirm!

Attached the screenshot about Rocket's message in share with friend
![device-2018-09-10-154238](https://user-images.githubusercontent.com/7045016/45283519-b1afe900-b510-11e8-92d3-0dcf537b68ef.png)

**Comment by weslyhuang** [comment]
tks benjamin, so pending on onboarding strings from the marketing team.

**Comment by benjamin-cheng** [comment]
@elin-moco Could you help to provide the app google play link with marketing campaign like we did in Rocket?

**Comment by weslyhuang** [comment]
maybe this is pending on a new GooglePlay page for "the app with a new package name (for ASO)"?

**Comment by elin-moco** [comment]
@benjamin-cheng 
I've created using adjust and bitly.
https://mzl.la/2NMgD30
