### ISSUE TITLE
It should trigger a reminder to explain why we need users to enable capture when users open the app

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#76]
1. Disable capturing
2. Re-open Scryer

Expected Result:
 - When users open Scryer, it triggers a reminder to explain why we need users to enable capture

Actual Result:
 - No Reminder in Home view
 - Video: https://drive.google.com/open?id=13I5PbS3TvOgDl4EyKM2mmROioWa3a3iw

Scryer 1.0(173).debug
Pixel2
Android 8.1.0

**Comment by ChenMorpheus** [comment]
Please find the attached for more details. Besides, we had a conclusion that we’ll define the prompt rule based on the Telemetry data in open-beta, and for the reminder panel of unsorted screenshot as well.

![image](https://user-images.githubusercontent.com/18019946/45283825-7c57cb00-b511-11e8-8a38-681a83881502.png)

**Comment by weslyhuang** [comment]
still MVP so S1
