### ISSUE TITLE
2.5 Empty content: Missing string "No screenshots yet!" when there is no screenshot in a collection

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#79]
STR
 1. Launch Scryer
 2. Create a collection 

Expected Result:
 - When there is no screenshot in a collection, display the message to inform users to move screenshots into to collection
(UX spec: 2.5B)

Actual Result:
 - The string should be "No screenshots yet!"
![screenshot_2018-09-05-05-36-10-81 1](https://user-images.githubusercontent.com/12458450/45087364-29a89880-b138-11e8-96f3-0482abaf698f.png)

Scryer 1.0(175).debug
OPPO A37f
Android 5.1.1

**Comment by weslyhuang** [comment]
not complying UX spec.

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2 
Android 8.1.0
ScreenshotGo 1.0(454).nightly
