### ISSUE TITLE
Crash when user tries to share screenshots

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Scryer#86]
Prerequisite:
Preexisting screenshots

STR:

1. Launch Scryer
2. View all screenshots under quick access
3. Long press on a shot and tap share

Expected result:
System share panel should shows up with a list of apps to choose to share the screenshot

Actual result:
App crashes

Reproduce Rate: only sharing certain shots will cause crash

Device: Redmi 4A
Scryer Ver.: 1.0(180).debug
Android Ver.: 7.1.2
WebView/Chrome: 68.0.3440.91 

Clip: 
https://drive.google.com/open?id=19kvsXvIGOiuLl3yESUkadhm733f5s981

Log:
[scryer_crash_0906.txt](https://github.com/mozilla-tw/Scryer/files/2355521/scryer_crash_0906.txt)

**Comment by sholkayvishal** [comment]
Can I work on this issue? 
P.S I don't know if I can fix it or not but I want to try.

**Comment by mxlius** [comment]
@sholkayvishal Thanks for your attention on us, and always, patches are welcome. 😄 
However, we're getting close to our RC date, so we probably will fix this in a very short time. You can still have your PR ready, then maybe we can merge it later as a complete solution.
Happy coding!

**Comment by weslyhuang** [comment]
same for me here, should be 100% reproducible so S1 and P1.

nightly build 202
android 8.0.0
S8+
