### ISSUE TITLE
Missing button "X" in "Give feedback" page

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Scryer#96]
1. Launch Scryer
2. Go to Menu -> Settings -> Give feedback

Expected Result:
 - There is an "X" button to close the Message

Actual Result:
 - No "X" button 

Scryer 1.0(191).nightly
All devices

**Comment by benjamin-cheng** [comment]
User can use back button or tap anywhere outside the dialog to leave. Also there is no "X" in the visual spec. Need UX/VD to confirm.

**Comment by ChenMorpheus** [comment]
The intention to have "X" in the dialogue was to align with Rocket's design to alleviate implementing efforts. However, it seems to become an extra effort for now. So I removed the "X" and updated the UX spec accordingly.

![image](https://user-images.githubusercontent.com/18019946/45279488-e1a4bf80-b503-11e8-8f83-11eb1f06baab.png)

**Comment by cynthiatang** [comment]
Hi @ChenMorpheus , thanks for your update. I'd like to close this issue.
